import { createHash } from "node:crypto"
import { existsSync, readFileSync } from "node:fs"
import { runInNewContext } from "node:vm"

import { describe, expect, it } from "vitest"

import { bucket, VARIANT_SALT } from "../src/hash.ts"
import { keyNamespace } from "../src/key.ts"
import { RESERVED_NAMES } from "../src/limits.ts"
import type { SnippetEntry } from "../src/types.ts"
import { readJson, root } from "./read.ts"

// Generated by the Laravel app (tests/Fixtures/flags); a changed file must come from there.
const pinned: Record<string, string> = {
  "flag-eval.cases.json": "a4cd7b9a38311a08d63b8c5953c0b7a808210f9bf5960a71642978e71235c6f6",
  "flag-hash.cases.json": "dadad6aa56a74aa0788091ebaf44b5bc7d119303b3e2450e0cda4faea55569fe",
  "page-snippet.cases.json": "e3572e307b6df6983895ecc4146e8b3aa8c5ff4f3ea0b2dd0aad15cf694b5598",
  "reserved-names.json": "1c8d9d3c111dd0de8c9b160786f7f11132b38d730924d7cdb4e9843f062faa84"
}

const sha256 = (file: URL): string => createHash("sha256").update(readFileSync(file)).digest("hex")

const app = new URL("../app/tests/Fixtures/flags/", new URL("../", root))

describe("server fixtures", () => {
  it.each(Object.entries(pinned))("%s is the pinned copy", (name, hash) => {
    expect(sha256(new URL(`fixtures/${name}`, root))).toBe(hash)
  })

  it.skipIf(!existsSync(app)).each(Object.keys(pinned))("%s equals the Laravel checkout", (name) => {
    expect(sha256(new URL(`fixtures/${name}`, root))).toBe(sha256(new URL(name, app)))
  })

  it("reserves the names the server reserves", () => {
    expect(RESERVED_NAMES.toSorted()).toEqual(
      readJson<{ names: string[] }>("fixtures/reserved-names.json").names.toSorted()
    )
  })
})

interface Snippet {
  readonly key: string
  readonly ingestKey: string
  readonly namespace: string
  readonly script: string
}

interface SnippetCase {
  readonly name: string
  readonly snippet: string
  readonly url: string
  readonly now: number
  readonly signal?: unknown
  readonly storage?: Record<string, string>
  readonly pending?: string
  readonly uuid?: string
  readonly bytes?: number[]
  readonly dnt?: string
  readonly gpc?: boolean
  readonly ignore?: boolean
  readonly prerendering?: boolean
  readonly expect: {
    readonly attribute: string
    readonly entry: SnippetEntry | null
    readonly pending: string | null
    readonly storageReads: number
  }
}

const snippets = readJson<{ snippets: Record<string, Snippet>; cases: SnippetCase[] }>(
  "fixtures/page-snippet.cases.json"
)

const snippetOf = (name: string): Snippet => {
  const snippet = snippets.snippets[name]

  if (!snippet) {
    throw new Error(`no snippet ${name}`)
  }

  return snippet
}

describe("page snippets", () => {
  it.each(Object.values(snippets.snippets))(
    "namespaces $ingestKey like the SDKs",
    ({ ingestKey, namespace }) => {
      expect(keyNamespace(ingestKey)).toBe(namespace)
    }
  )

  it.each(snippets.cases)("$name", (fixture) => {
    const snippet = snippetOf(fixture.snippet)
    const url = new URL(fixture.url)
    const attributes: Record<string, string> = {}
    let reads = 0
    const window: Record<string, unknown> = {
      __mirafive_consent: fixture.signal,
      __mirafive_ignore: fixture.ignore,
      __mirafive_aid_next: fixture.pending,
      crypto: {
        ...(fixture.bytes ? {} : { randomUUID: () => fixture.uuid }),
        getRandomValues: (array: Uint8Array) => {
          array.set(fixture.bytes ?? [])

          return array
        }
      },
      document: {
        documentElement: { setAttribute: (name: string, value: string) => (attributes[name] = value) },
        prerendering: fixture.prerendering
      },
      navigator: { doNotTrack: fixture.dnt, globalPrivacyControl: fixture.gpc },
      location: { search: url.search, hostname: url.hostname },
      localStorage: {
        getItem: (key: string) => {
          reads += 1

          return fixture.storage?.[key] ?? null
        }
      }
    }

    window["window"] = window
    runInNewContext(`Date.now = () => ${fixture.now};${snippet.script}`, window)

    const entry = (window["__mirafive_experiments"] as SnippetEntry[] | undefined)?.[0] ?? null

    expect(
      JSON.parse(
        JSON.stringify({
          attribute: attributes[`data-mirafive-${snippet.key}`],
          entry,
          pending: window["__mirafive_aid_next"] ?? null,
          storageReads: reads
        })
      )
    ).toEqual(fixture.expect)

    if (entry) {
      const stored = Object.values(fixture.storage ?? {})[0]?.split(".")[0]
      const id = fixture.expect.pending ?? stored ?? ""
      let point = bucket(entry.s, VARIANT_SALT, id)
      const variant = ["a", "b"].find((_, index) => (point -= entry.w[index] ?? 0) < 0)

      expect(variant).toBe(entry.v)
    }
  })
})
